DEVICE: cuda  # or 'cpu'

NUM_OF_GPU_TRAIN: 1
TRAIN:
  EPOCHS: 100
  LR: 0.0001
  BATCH_SIZE: 8
  PLOT_LOSSES_AND_LR: True
  MODEL_FILE_NAME: 'physformer_model'
  DATA:
    PREPROCESS:
      CHUNK_LENGTH: 64
      RESIZE:
        H: 128
        W: 128
      FS: 30  # frame rate
  TOOLBOX_MODE: 'train_and_test'  # Options: 'train_and_test', 'only_test'
  TEST:
    USE_LAST_EPOCH: False

MODEL:
  MODEL_DIR: './models'
  DROP_RATE: 0.1
  PHYSFORMER:
    PATCH_SIZE: 16
    DIM: 512
    FF_DIM: 2048
    NUM_HEADS: 8
    NUM_LAYERS: 6
    THETA: 0.1

INFERENCE:
  MODEL_PATH: './models/physformer_best_model.pth'

